---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: '3000'
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.network/echo-server-default: 'true'
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: PORT
              value: '3000'
            - name: URL_BIG_IP
              valueFrom:
                configMapKeyRef:
                  key: URL_BIG_IP
                  name: env
          image: xpop/echo_server
          name: app
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
data:
  URL_BIG_IP: https://bigip-01.example.com
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: app-env
  name: env
